FROM local/c7-systemd
RUN yum -y install nginx; yum clean all; systemctl enable nginx
RUN  rm -rf /usr/share/nginx/html/*
copy WebStatic /usr/share/nginx/html
copy roboshop.config /etc/nginx/default.d/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


